"""Build (or verify) the single-file executor script from the two local Lua sources.

`HttpSpy.standalone.lua` embeds `Serializer.lua` directly, so the raw-loadstring
version of the spy never downloads the serializer at runtime.

    python3 tools/build_standalone.py           # (re)generate HttpSpy.standalone.lua
    python3 tools/build_standalone.py --check   # verify it is in sync (non-zero exit if not)

The script never touches the network and only reads the two source modules.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPY = ROOT / "HttpSpy.lua"
SERIALIZER = ROOT / "Serializer.lua"
STANDALONE = ROOT / "HttpSpy.standalone.lua"

# The one line in HttpSpy.lua that connects the two ModuleScripts locally.
LOADER = "local Serializer = require(script.Parent.Serializer)"
# Serializer.lua is a ModuleScript, so it ends by returning its table.
MODULE_RETURN = "return Serializer;"
GENERATED_HEADER = "-- Generated by tools/build_standalone.py; edit the source modules instead.\n"

# A standalone build must never reference these.
FORBIDDEN_IN_OUTPUT = (
    "raw.githubusercontent.com",
    "require(script.Parent.Serializer)",
)


def read(path: Path) -> str:
    """Read text without newline translation so builds are byte-stable."""
    with path.open("r", encoding="utf-8", newline="") as handle:
        return handle.read()


def write(path: Path, text: str) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        handle.write(text)


def build() -> str:
    spy = read(SPY)
    serializer = read(SERIALIZER)

    if spy.count(LOADER) != 1:
        raise SystemExit(
            f"error: expected exactly one occurrence of {LOADER!r} in {SPY.name}, "
            f"found {spy.count(LOADER)}"
        )
    if not serializer.rstrip().endswith(MODULE_RETURN):
        raise SystemExit(
            f"error: {SERIALIZER.name} must end with {MODULE_RETURN!r} so it can be embedded"
        )

    body = serializer.rstrip()[: -len(MODULE_RETURN)]
    embedded = f"local Serializer = (function()\n{body}return Serializer\nend)()"
    output = GENERATED_HEADER + spy.replace(LOADER, embedded)

    if output.count("local Serializer = (function()") != 1:
        raise SystemExit("error: expected exactly one embedded serializer block in the output")
    for forbidden in FORBIDDEN_IN_OUTPUT:
        if forbidden in output:
            raise SystemExit(f"error: generated standalone still contains {forbidden!r}")

    return output


def main(argv: list[str]) -> int:
    check = "--check" in argv
    output = build()

    if check:
        if not STANDALONE.exists():
            print(f"FAIL {STANDALONE.name} is missing; run `python3 tools/build_standalone.py`")
            return 1
        if read(STANDALONE) != output:
            print(
                f"FAIL {STANDALONE.name} is out of sync with "
                f"{SPY.name} + {SERIALIZER.name}; run `python3 tools/build_standalone.py`"
            )
            return 1
        print(f"OK   {STANDALONE.name} is in sync with the source modules ({len(output)} bytes)")
        return 0

    write(STANDALONE, output)
    print(f"wrote {STANDALONE} ({len(output)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
