"""Build a single-file executor script from the two local Lua sources."""
from pathlib import Path

root = Path(__file__).resolve().parent.parent
spy = (root / 'HttpSpy.lua').read_text()
serializer = (root / 'Serializer.lua').read_text()
loader = 'local Serializer = require(script.Parent.Serializer)'
assert spy.count(loader) == 1, 'HttpSpy serializer loader changed'
assert serializer.rstrip().endswith('return Serializer;'), 'Serializer module return changed'
embedded = serializer.rstrip()[:-len('return Serializer;')]
spy = spy.replace(loader, 'local Serializer = (function()\n' + embedded + 'return Serializer\nend)()')
output = root / 'HttpSpy.standalone.lua'
output.write_text('-- Generated by tools/build_standalone.py; edit the source modules instead.\n' + spy)
print(output)
